### ISSUE TITLE
Light clean bug with chunks

### ISSUE THREAD

**Issue by Hdadaw** [bergerhealer/Light-Cleaner#5]
Very often I see such problems at the ends of chunks after "/cleanlight" command:
![2017-11-05_09 59 13](https://user-images.githubusercontent.com/32250813/32411193-3680dac6-c210-11e7-9f65-af29be934aae.png)
![2017-11-05_10 02 48](https://user-images.githubusercontent.com/32250813/32411205-823ea98e-c210-11e7-89ec-c6e45b9486b7.png)

**Comment by bergerkiller** [comment]
Are these bugs happening within the area the cleanlight command fixes, or at the chunk border of the area being fixed? It loads the full region to be fixed into memory and operates on it as a whole, so its surprising to see it have problems at the borders. Noted.

**Comment by Hdadaw** [comment]
@bergerkiller I just write / cleanlight and then sometimes see such problems.
another bug:
![2017-11-11_17 44 05](https://user-images.githubusercontent.com/32250813/32688242-3ceb4f20-c708-11e7-8ec5-e63b238720e9.png)

**Comment by bergerkiller** [comment]
That definitely does look like something I need to take a good look at.

**Comment by Hdadaw** [comment]
I noticed that in a new 1.12.2-v1 version in some places such problems have been fixed, but not in all places:
![2017-12-02_17 03 31](https://user-images.githubusercontent.com/32250813/33513710-543f8836-d783-11e7-9afb-4d62f2880739.png)

**Comment by bergerkiller** [comment]
I'll quote from the Spigot page:

Minecraft completely deletes chunk slices (16x16x16 blocks) when all blocks in it are air. As a result, no lighting information can be stored in there. Blocks that touch these 'no-light' zones show up as very dark lighting sometimes. This is a Minecraft bug that can't easily be fixed. You can work around it by moving the surface touching this empty slice by one block, or by placing a block in the empty slice so it is no longer empty. A single barrier block can make minecraft see it as non-empty, allowing light to be saved.

This is primarily a problem in nether worlds where empty slices default to a dark color, instead of light like in overworlds.

Is the area directly facing the bugged area a completely empty 16x16x16 area of air?

**Comment by Hdadaw** [comment]
If i correct the light by placing and breaking blocks, after the command "/cleanlight" it again sets light level to 0. 

You can generate my world by using seed and this server core: 
![image](https://user-images.githubusercontent.com/32250813/33518128-c14f98e8-d7ca-11e7-9cf9-9aac266041bd.png)

![image](https://user-images.githubusercontent.com/32250813/33518119-b5c79156-d7ca-11e7-8c20-1a3ad6552757.png)

**Comment by Hdadaw** [comment]
@bergerkiller bump

**Comment by bergerkiller** [comment]
Im currently busy fixing up TrainCarts and BKCommonLib for the next release, so it'll take a little while until I can really move my focus to this issue unfortunately :(

**Comment by bergerkiller** [comment]
Confirmed the bug (after flying for a couple minutes to the exact coordinates). Glad the seed worked. I'll try and fix this now. It also occurs on 1.12.2, ruling out anything specific to 1.11.2.

**Comment by bergerkiller** [comment]
Well that was a really dumb bug. Super easy to find and fix (once you have a spot to reproduce it-). I had mixed up the dy with dz, resulting in the mechanic that informs neighbouring chunks of changed lighting to fail. Basically, it thought a chunk was done cleaning the light when that is not yet the case. It is very difficult to consistently reproduce though, which is probably why I had never found it before.

This version should fix this problem: https://ci.mg-dev.eu/job/Light-Cleaner/22/

**Comment by Hdadaw** [comment]
Yeah, now it works correctly, thanks!

**Comment by Hdadaw** [comment]
But now I noticed that it does not fix the generated chunks with the wrong light from the tree:
![2018-01-01_20 59 39](https://user-images.githubusercontent.com/32250813/34467834-d233ae50-ef36-11e7-9b48-e0605f780e77.png)
world seed and version of server has not changed

**Comment by bergerkiller** [comment]
Confirmed the bug, but it turns out to exist in BKCommonLib too. It doesnt appear to recognize that the world has sky light, so its not fixing any at all. Working on a fix.

**Comment by bergerkiller** [comment]
Can you verify whether this build of BKCommonLib fixes these problems? I couldn't reproduce any bugs after on my server. The bug I found wasnt actually at that cliff but nearby. https://ci.mg-dev.eu/job/BKCommonLib/334/

**Comment by Hdadaw** [comment]
Yes, now the light in this place has been corrected. Thanks again

**Comment by minexew** [comment]
Just wanted to drop in and say THANK YOU for this great plugin <3

**Comment by bergerkiller** [comment]
Awh thanks :)
